# Providing this file adds a "❤ Sponsor" button for the repo
# These are various supported funding model platforms; we use a custom one
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# add ?ref=PROJECT_NAME to see the referrer
custom: ["https://justinbriggs.net/tips/?ref=zenhome"]
